### ISSUE TITLE
v7 repositories?

### ISSUE THREAD

**Issue by jjlee** [datalad/datalad.org#56] opened 2019-02-17 17:58 UTC
Is there any documentation on the interaction between git annex repo format and datalad?  In particular, is datalad happy with annex v7?  Are there any gotchas with using datalad with annex v7 format?

**Comment by mih** [comment] 2019-02-17 18:31
I have been using v7 (and before that v6) repos for quite some time. I am not aware of fundamental issues, besides a possible race condition that could leave an annexed file being reported as modified by Git, possibly because the filter that tests its modification is taking too long.

That being said, I have never observed this in real use, but it pops up in the tests.

**Comment by mih** [comment] 2019-02-17 18:35
I am closing this issue here. This is the repo of the datalad website. Please reopen at https://github.com/datalad/datalad for further discussion.

**Closed by mih** 2019-02-17 18:35 UTC

**Comment by yarikoptic** [comment] 2019-02-17 19:20
@jjlee if you happen to be a Windows user though, most recent git annex got sever regression http://git-annex.branchable.com/bugs/windows_support_totally_bitrotted/
so watch out
